package scaffold

import (
	"bytes"
	"fmt"
	"text/template"
)

// Choice is the fully-resolved set of decisions a rendered stack is built from:
// the accelerator variant, the chat LLM and the TTS voice. The VAD and
// transcription stages are fixed (see the package-level constants).
type Choice struct {
	Variant Variant
	LLM     string
	TTS     string
}

// composeData is the template payload. Everything the template needs is
// precomputed here so the template stays declarative and output is deterministic
// (no map ranging, no time, no host state).
type composeData struct {
	Image         string
	DeviceStanza  string
	LLM           string
	TTS           string
	Transcription string
	VAD           string
}

// RenderCompose renders a complete, runnable docker-compose.yml for the given
// Choice. Output is deterministic: identical Choices always produce byte-identical
// files (golden-testable). It mirrors the structure and comments of the
// hand-written compose so a generated stack reads the same as the checked-in one.
func RenderCompose(c Choice) ([]byte, error) {
	data := composeData{
		Image:         c.Variant.Image,
		DeviceStanza:  c.Variant.DeviceStanza,
		LLM:           c.LLM,
		TTS:           c.TTS,
		Transcription: TranscriptionModel,
		VAD:           VADModel,
	}
	var buf bytes.Buffer
	if err := composeTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render compose: %w", err)
	}
	return buf.Bytes(), nil
}

// composeTemplate is the scaffolded LocalAI realtime backend stack. {{.DeviceStanza}}
// is emitted verbatim (it's pre-indented YAML) only for GPU variants.
var composeTemplate = template.Must(template.New("compose").Parse(`# Self-contained LocalAI realtime backend for the demo client.
# Generated by 'assistant setup' for this host's hardware.
#
#   docker compose up
#
# Starts LocalAI on http://localhost:8080, installs the sub-models the realtime
# pipeline needs (VAD, STT, LLM, TTS) from the gallery on first start, and
# serves the pipeline at:
#
#   ws://localhost:8080/v1/realtime?model=gpt-realtime
#
# First start downloads model weights, so give it a few minutes (watch the logs;
# ` + "`/readyz`" + ` flips healthy once it's up). Weights are cached in ./localai/models,
# so later starts are fast. Then run the client from the repo root:
#
#   go build -o assistant ./cmd/assistant && ./assistant -model gpt-realtime
#
services:
  localai:
    # Image variant picked for this host's accelerator by 'assistant setup'.
    image: {{.Image}}
    container_name: localai-realtime
    ports:
      # Host port is overridable (LOCALAI_PORT) for when 8080 is already taken;
      # if you change it, point the client at it with -ws-url.
      - "${LOCALAI_PORT:-8080}:8080"
    environment:
      # Set DEBUG=true to watch model loading in detail.
      - DEBUG=false
    volumes:
      # The pipeline config (gpt-realtime.yaml) lives here; the gallery-installed
      # sub-model configs and their weights are cached here too (git-ignored).
      - ./localai/models:/models:z
{{- if .DeviceStanza}}
{{.DeviceStanza}}
{{- end}}
    # Positional args install + load these gallery models at startup; the
    # pipeline (gpt-realtime.yaml) references them by name. Order: VAD, STT, the
    # chosen LLM, the chosen TTS voice.
    command:
      - {{.VAD}}
      - {{.Transcription}}
      - {{.LLM}}
      - {{.TTS}}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 15s
      timeout: 10s
      retries: 40
      start_period: 30s
    restart: unless-stopped
`))
